### ISSUE TITLE
In dark mode, the text is hard to distinguish

### ISSUE THREAD

**Issue by tianheg** [alephpi/alephpi.github.io#1]
![image](https://github.com/alephpi/alephpi.github.io/assets/52186032/85572ddb-947a-4e80-85e0-dcfe2945cf76)

**Comment by alephpi** [comment]
Hi, can you provide more details? Since it displays well on my device, the text color is actually #FFFFFF and the contrast is appropriate.
![image](https://github.com/alephpi/alephpi.github.io/assets/61275421/d646d96f-ad59-4ecd-afca-7cfd7d9ae3d8)

**Comment by tianheg** [comment]
I found the problem, in your CSS, you used

```css
body {
  -moz-osx-font-smoothing: grayscale;
}
```

to make the text lighter.

> The `-moz-osx-font-smoothing: grayscale` is a Firefox-specific CSS property that controls the application of anti-aliasing to fonts when rendered on Mac OS X.
>
> Setting it to `grayscale` applies anti-aliasing in a way that can make the text look lighter overall. This is similar to subpixel-optimized rendering provided by `-webkit-font-smoothing: antialiased`.
>
> from GitHub Copilot

However I use Archlinux with Firefox Developer Edition :)

**Comment by alephpi** [comment]
Then how to fix it? Actually I just use the vitepress theme and don't touch this css setting. Maybe you can raise an issue for [vitepress](https://github.com/vuejs/vitepress).

**Comment by tianheg** [comment]
New problem: I'm running a Vitepress site https://read.tianheg.org/ , switching to darktheme still see text clearly.

Maybe I found the answer: The style for your `<a>` tag has been defined twice:

```css
a {
  color: inherit;
}
.vp-doc a {
  color: var(--vp-c-brand-1);
}
```

Step:

1. Open your site `https://alephpi.github.io/article/` in Firefox private window to avoid interference from browser extensions
2. Check the color property one by one, found the most likely answer

Looking forward your reply

**Comment by alephpi** [comment]
Indeed, now should be ok. Thank you very much!
